"use server";

import OpenAI from "openai";

// Initialize OpenAI client
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

/**
 * Generate a concise title for any activity (listing or contact) based on notes and action
 * Uses OpenAI to create a meaningful, short title (50-60 characters)
 *
 * @param notes - The activity notes/description
 * @param action - The action type (email_sent, call_logged, etc.)
 * @param activityType - Optional activity type from modal (mail, whatsapp, call, visit, otros)
 * @returns A concise title generated by OpenAI, or throws an error
 */
export async function generateActivityTitle(
  notes: string,
  action?: string,
  activityType?: string,
): Promise<string> {
  try {
    if (!notes?.trim()) {
      throw new Error("Notes are required to generate title");
    }

    // Map activity types to Spanish labels for context
    const activityTypeLabels: Record<string, string> = {
      mail: "Email",
      whatsapp: "WhatsApp",
      call: "Llamada",
      visit: "Visita en Persona",
      otros: "Otros",
    };

    const activityContext = activityType
      ? activityTypeLabels[activityType] ?? activityType
      : "";

    // Create a focused prompt for title generation
    const contextLine = activityContext ? `Tipo de actividad: ${activityContext}\n\n` : "";
    const prompt = `Genera un título conciso en español (máximo 60 caracteres) para esta actividad de contacto inmobiliario:

${contextLine}${notes.trim()}

Requisitos:
- Máximo 60 caracteres (estrictamente)
- Captura la esencia principal de la actividad
- Sé específico y descriptivo
- Usa un lenguaje profesional pero directo
- Enfócate en la acción o resultado principal mencionado
- Sin palabras innecesarias o contenido de relleno
- Debe ser útil para identificar rápidamente la actividad en una lista

Genera un título conciso que resuma la esencia de esta actividad:`;

    // Call OpenAI API for title generation
    const completion = await openai.chat.completions.create({
      messages: [
        {
          role: "system",
          content: `Eres un experto en generar títulos concisos y descriptivos para actividades de contacto inmobiliario. Tu especialidad es crear títulos breves (máximo 60 caracteres) que capturen la esencia principal de la actividad descrita en español.

Principios clave:
- Extrae la acción o resultado principal mencionado
- Sé específico y descriptivo
- Usa lenguaje profesional pero directo
- Enfócate en lo más importante de la actividad
- Sin palabras innecesarias - cada carácter cuenta
- Prioriza la claridad y la utilidad para identificación rápida
- Mantén un tono profesional apropiado para contextos inmobiliarios
- SIEMPRE debes devolver un título, nunca una respuesta vacía`,
        },
        {
          role: "user",
          content: prompt,
        },
      ],
      model: "gpt-5-mini-2025-08-07",
      // Note: This model might not support max_completion_tokens, removing it to match property_descriptions.tsx
    });

    // Verify response structure
    if (!completion?.choices || completion.choices.length === 0) {
      console.error("❌ [OpenAI] No choices in completion response");
      throw new Error("OpenAI returned no choices");
    }

    const rawContent = completion.choices[0]?.message?.content;

    if (!rawContent) {
      throw new Error("OpenAI returned no content");
    }

    const title = rawContent.trim();

    if (!title || title.length === 0) {
      throw new Error("OpenAI returned empty title");
    }

    // Ensure it's within the character limit
    if (title.length > 60) {
      return title.substring(0, 57) + "...";
    }

    return title;
  } catch (error) {
    console.error("Error generating activity title:", error);
    throw new Error("Failed to generate activity title");
  }
}

/**
 * Generate a title for an activity from its details object
 * Convenience wrapper that extracts notes and action from details
 *
 * @param action - The action type
 * @param details - The activity details object
 * @returns A concise title generated by OpenAI, or falls back to a simple title
 */
export async function generateActivityTitleFromDetails(
  action: string,
  details: Record<string, unknown>,
): Promise<string | null> {
  try {
    const notes = (details as { notes?: string })?.notes;
    const activityType = (details as { activityType?: string })?.activityType;

    // If no notes, return null (will use default label)
    if (!notes?.trim()) {
      return null;
    }

    return await generateActivityTitle(notes, action, activityType);
  } catch (error) {
    console.error("Error generating title from details:", error);
    return null; // Fall back to default label
  }
}

