#!/usr/bin/env tsx
/**
 * Schema Conversion Script: SingleStore → PostgreSQL (Supabase)
 *
 * This script automatically converts your Drizzle schema from SingleStore to PostgreSQL.
 *
 * Usage:
 *   npx tsx scripts/convert-schema-to-postgres.ts
 *
 * Output:
 *   - src/server/db/schema.postgres.ts (converted schema)
 *   - supabase/migrations/001_initial_schema.sql (migration SQL)
 *   - supabase/migrations/002_triggers.sql (update triggers)
 */

import * as fs from "fs";
import * as path from "path";

const SCHEMA_INPUT = path.join(process.cwd(), "src/server/db/schema.ts");
const SCHEMA_OUTPUT = path.join(
  process.cwd(),
  "src/server/db/schema.postgres.ts",
);
const MIGRATION_DIR = path.join(process.cwd(), "supabase/migrations");

console.log("🔄 Starting schema conversion: SingleStore → PostgreSQL\n");

// Read the original schema
console.log("📖 Reading schema from:", SCHEMA_INPUT);
let schemaContent = fs.readFileSync(SCHEMA_INPUT, "utf-8");

// Conversion Step 1: Update imports
console.log("✏️  Converting imports...");
schemaContent = schemaContent.replace(
  /from ["']drizzle-orm\/singlestore-core["']/g,
  'from "drizzle-orm/pg-core"',
);

// Conversion Step 2: Replace singlestoreTable with pgTable
console.log("✏️  Converting table definitions...");
schemaContent = schemaContent.replace(/singlestoreTable/g, "pgTable");

// Conversion Step 3: Convert json() to jsonb()
console.log("✏️  Converting JSON types to JSONB...");
schemaContent = schemaContent.replace(
  /: json\("([^"]+)"\)/g,
  ': jsonb("$1")',
);

// Conversion Step 4: Remove .onUpdateNow() (will be handled by triggers)
console.log("✏️  Removing .onUpdateNow() (will use triggers instead)...");
schemaContent = schemaContent.replace(/\.onUpdateNow\(\)/g, "");

// Conversion Step 5: Handle BigInt mode
console.log("✏️  Updating BigInt handling...");
// Keep { mode: "bigint" } for PostgreSQL
// PostgreSQL returns bigints as strings by default in node-postgres

// Conversion Step 6: Add serial/bigserial for auto-increment
// This is already handled by .autoincrement() in Drizzle

// Write the converted schema
console.log("💾 Writing converted schema to:", SCHEMA_OUTPUT);
fs.writeFileSync(SCHEMA_OUTPUT, schemaContent, "utf-8");

// Generate migration SQL
console.log("\n📝 Generating migration SQL files...");

// Create migrations directory
if (!fs.existsSync(MIGRATION_DIR)) {
  fs.mkdirSync(MIGRATION_DIR, { recursive: true });
}

// Generate timestamp update triggers SQL
const triggerSQL = `-- Timestamp Update Triggers
-- Auto-update updated_at column on row updates

-- Create trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply trigger to all tables with updated_at column
DO $$
DECLARE
    t text;
BEGIN
    FOR t IN
        SELECT table_name
        FROM information_schema.columns
        WHERE table_schema = 'public'
        AND column_name = 'updated_at'
    LOOP
        EXECUTE format('
            DROP TRIGGER IF EXISTS update_%I_updated_at ON %I;
            CREATE TRIGGER update_%I_updated_at
                BEFORE UPDATE ON %I
                FOR EACH ROW
                EXECUTE FUNCTION update_updated_at_column();
        ', t, t, t, t);
    END LOOP;
END $$;

-- Verify triggers created
SELECT
    trigger_name,
    event_object_table
FROM information_schema.triggers
WHERE trigger_schema = 'public'
ORDER BY event_object_table;
`;

fs.writeFileSync(
  path.join(MIGRATION_DIR, "002_triggers.sql"),
  triggerSQL,
  "utf-8",
);

// Create helpful README for migrations
const migrationReadme = `# Supabase Migrations

## Files

- \`001_initial_schema.sql\` - Generated by \`drizzle-kit push\`
- \`002_triggers.sql\` - Auto-update triggers for updated_at columns

## Applying Migrations

### Option 1: Using Drizzle Kit (Recommended)

\`\`\`bash
# Generate migration from schema
drizzle-kit generate --config=drizzle.config.postgres.ts

# Push schema to Supabase
drizzle-kit push --config=drizzle.config.postgres.ts
\`\`\`

### Option 2: Using psql

\`\`\`bash
# Apply schema
psql "$POSTGRES_URL_NON_POOLING" -f supabase/migrations/001_initial_schema.sql

# Apply triggers
psql "$POSTGRES_URL_NON_POOLING" -f supabase/migrations/002_triggers.sql
\`\`\`

### Option 3: Using Supabase CLI

\`\`\`bash
# Initialize Supabase
supabase init

# Link to project
supabase link --project-ref your-project-ref

# Push migrations
supabase db push
\`\`\`

## Verification

After applying migrations, verify:

\`\`\`sql
-- List all tables
\\dt

-- Check triggers
SELECT trigger_name, event_object_table
FROM information_schema.triggers
WHERE trigger_schema = 'public';

-- Verify columns
\\d+ users
\\d+ properties
\\d+ listings
\`\`\`
`;

fs.writeFileSync(
  path.join(MIGRATION_DIR, "README.md"),
  migrationReadme,
  "utf-8",
);

console.log("✅ Created:", path.join(MIGRATION_DIR, "002_triggers.sql"));
console.log("✅ Created:", path.join(MIGRATION_DIR, "README.md"));

// Generate conversion summary
console.log("\n" + "=".repeat(60));
console.log("✅ SCHEMA CONVERSION COMPLETE");
console.log("=".repeat(60));
console.log("\n📋 Summary of Changes:");
console.log("  - Imports updated: singlestore-core → pg-core");
console.log("  - Tables converted: singlestoreTable → pgTable");
console.log("  - JSON types converted: json → jsonb");
console.log("  - onUpdateNow() removed (replaced with triggers)");
console.log("  - BigInt handling preserved");

console.log("\n📁 Generated Files:");
console.log("  ✓", SCHEMA_OUTPUT);
console.log("  ✓", path.join(MIGRATION_DIR, "002_triggers.sql"));
console.log("  ✓", path.join(MIGRATION_DIR, "README.md"));

console.log("\n🔧 Next Steps:");
console.log("  1. Review the converted schema file");
console.log("  2. Create drizzle.config.postgres.ts");
console.log("  3. Generate initial migration:");
console.log("     drizzle-kit generate --config=drizzle.config.postgres.ts");
console.log("  4. Push schema to Supabase:");
console.log("     drizzle-kit push --config=drizzle.config.postgres.ts");
console.log("  5. Apply triggers:");
console.log(
  "     psql \"$POSTGRES_URL_NON_POOLING\" -f supabase/migrations/002_triggers.sql",
);
console.log("\n✨ Happy migrating!\n");
